#pragma once

#define kGameFacadeTypeInfo      0xAFF1A58
#define kTypeInfoStatics         0xB8
#define kCurrentGame             0x0
#define kCurrentMatchGame        0x8
#define kMatch                   0x90
#define kMatchLocalPlayer        0xD8
#define kCameraControllerManager 0xD8

#define kMainCamera              0x20
#define kCameraInner            0x10

#define kViewMatrixOff          0x80
#define kProjMatrixOff          0xC0
#define kBodyPartTransNode       0x10
#define kHeadNode               0x640
#define kHipNode                0x648
#define kLeftAnkleNode           0x678
#define kRightAnkleNode          0x680
#define kRightToeNode            0x690
#define kLeftToeNode             0x688
#define kLeftShoulderNode        0x660
#define kRightShoulderNode       0x668
#define kLeftHandNode            0x6C0
#define kRightHandNode           0x6B8
#define kLeftElbowNode           0x6D0
#define kRightElbowNode          0x6C8
#define kPlayerIDStruct         0x2D0
#define kPlayerID               0x3B0
#define kUserID                 0x3A0
#define kIsClientBot            0x448
#define kDataPool               0x70
#define kDataPoolInner          0x10
#define kDataPoolEntriesBase    0x20
#define kDataPoolEntryStride    0x8
#define kDataPoolValue          0x18
#define kAimRotation            0x5B4
#define kAimRotationAux         0x5C4
#define kIsFiring               0x770
#define kVisibleObj             0xA38
#define kVisibleObjFlags        0x10
#define kISVisibleCamera        0x1
#define kISVisibleDynamicPVS    0x100000
#define kISVisibleFPPMask       0xFFFBFFFF
#define kMainCameraTransform    0x390
#define kMyPhysXData            0x19E0
#define kPhxNpeononogeo         0x20
#define kGhgState               0x10
#define kKnocked                 0x1150
#define kMatchPlayerDict        0x148
#define kDictEntries            0x18
#define kDictCount              0x20
#define kIl2CppArrayMaxLength   0x18
#define kIl2CppArrayItems       0x20
#define kDictEntryStrideBytePlayer   24
#define kDictEntryValueOffByte       16
#define kTransformInner         0x10
#define kTransformMatrix        0x38
#define kTransformIndex         0x40
#define kMatrixList             0x18
#define kMatrixIndices          0x20
#define kNickname               0x438
#define kStringFirstChar        0x14
